join_room:
    path: /room/{roomId}/join
    controller: Mita\UranusSocketServer\Examples\Chat\Controllers\ChatController
    defaults:
        _middleware:
            - Mita\UranusSocketServer\Examples\Chat\Middlewares\AuthMiddleware
room_publish:
    path: /room/{roomId}/publish
    controller: Mita\UranusSocketServer\Examples\Chat\Controllers\ChatController
